import json

from github import Github, PullRequest

class GitHubUtils:
    """
    A utility class for interacting with the GitHub API.
    Encapsulates common operations like getting PR details, posting comments,
    and managing review metadata.
    """

    def __init__(self, github_token: str, repo_name: str, pr_number: int):
        """
        Initializes the GitHubUtils with necessary credentials and PR details.

        Args:
            github_token (str): GitHub Personal Access Token.
            repo_name (str): Full repository name (e.g., 'owner/repo').
            pr_number (int): Pull Request number.
        """
        self.g = Github(github_token)
        self.repo = self.g.get_repo(repo_name)
        self.pr = self.repo.get_pull(pr_number)
        print(f"GitHubUtils initialized for PR: {repo_name}#{pr_number}")

    def get_pr_details(self) -> PullRequest:
        """
        Returns the GitHub PullRequest object.
        """
        return self.pr

    def is_bot_requested_reviewer(self, bot_user: str) -> bool:
        """
        Checks if the bot has been requested as a reviewer for the PR.

        Args:
            bot_user (str): The GitHub username of the bot.

        Returns:
            bool: True if the bot is a requested reviewer, False otherwise.
        """
        try:
            # get_review_requests() returns a tuple: (users, teams)
            reviewers, teams = self.pr.get_review_requests()
            requested_reviewers = [r.login for r in reviewers]
            requested_teams = [t.name for t in teams]

            if bot_user in requested_reviewers:
                print(f"Bot '{bot_user}' found in requested reviewers.")
                return True
            if bot_user in requested_teams: # Assuming bot_user can also be a team name if configured
                print(f"Bot team '{bot_user}' found in requested teams.")
                return True
            print(f"Bot '{bot_user}' not requested as reviewer or in requested teams.")
            return False
        except Exception as e:
            print(f"Error checking requested reviewers: {e}")
            return False

    def get_pr_files(self) -> list:
        """
        Retrieves all files changed in the pull request.

        Returns:
            list: A list of File objects from the GitHub API.
        """
        try:
            files = list(self.pr.get_files())
            print(f"Retrieved {len(files)} files from PR.")
            return files
        except Exception as e:
            print(f"Error getting PR files: {e}")
            return []

    def get_cached_reviewed_lines(self) -> dict:
        """
        Retrieves previously reviewed lines from a special metadata comment.
        This helps in tracking what has been reviewed by the bot previously.
        """
        for comment in self.pr.get_issue_comments():
            if comment.body.startswith("<!-- dhp-pr-review-bot-meta"):
                try:
                    meta = json.loads(comment.body.split('\n', 1)[1])
                    print("Loaded cached reviewed lines from metadata comment.")
                    return meta.get("reviewed", {})
                except Exception as e:
                    print(f"Error parsing metadata comment: {e}")
                    continue
        print("No cached reviewed lines found.")
        return {}

    def post_metadata_comment(self, reviewed_lines_dict: dict):
        """
        Posts a metadata comment to track which lines have been reviewed.
        """
        meta = { "reviewed": reviewed_lines_dict }
        body = f"<!-- dhp-pr-review-bot-meta\n{json.dumps(meta, indent=2)}\n-->"
        self.pr.create_issue_comment(body)
        print("Metadata comment posted.")

    def post_pr_review_comments(self, ai_review_json: dict):
        """
        Posts the comprehensive PR review comments generated by the AI.
        This includes an overall review body and line-specific comments.

        Args:
            ai_review_json (dict): The JSON object containing the AI's review.
        """
        comments_for_github_review = []
        overall_review_body = []

        # --- PR Summary ---
        if ai_review_json.get("pr_summary"):
            overall_review_body.append(f"## PR Summary\n{ai_review_json['pr_summary']}")

        # --- Improvement Suggestions ---
        if ai_review_json.get("improvement_suggestions"):
            overall_review_body.append("\n## Improvement Suggestions")
            for i, suggestion in enumerate(ai_review_json["improvement_suggestions"]):
                overall_review_body.append(f"- {suggestion}")

        # --- Code Issues (Line Comments) ---
        if ai_review_json.get("code_issues"):
            overall_review_body.append("\n## Code Issues")
            for issue in ai_review_json["code_issues"]:
                path = issue.get("file")
                # GitHub's 'position' refers to the line number in the diff hunk for the new file.
                # It does not directly support commenting on 'deleted side right' with a line number.
                # We will only add line comments for 'added' or 'modified' lines.
                position = issue.get("line_number")
                comment_body = issue.get("comment")
                category = issue.get("category", "General")

                if path and position and comment_body:
                    # Append line comment for GitHub's create_review API
                    comments_for_github_review.append({
                        "path": path,
                        "position": position,
                        "body": f"**Code Issue ({category}):** {comment_body}"
                    })
                    # Also add to the overall review body for visibility
                    overall_review_body.append(f"- **{path}:{position} ({category}):** {comment_body}")
                elif comment_body:
                    # If no specific line/path, add to overall comments
                    overall_review_body.append(f"- **Code Issue ({category}):** {comment_body}")


        # --- Security Vulnerabilities (Line Comments) ---
        if ai_review_json.get("security_vulnerabilities"):
            overall_review_body.append("\n## Security Vulnerabilities")
            for vuln in ai_review_json["security_vulnerabilities"]:
                path = vuln.get("file")
                # Similar to code issues, position is for the new file in the diff.
                position = vuln.get("line_number")
                comment_body = vuln.get("comment")
                severity = vuln.get("severity", "Medium")
                category = vuln.get("category", "General Security")

                if path and position and comment_body:
                    # Append line comment for GitHub's create_review API
                    comments_for_github_review.append({
                        "path": path,
                        "position": position,
                        "body": f"🚨 **Security Vulnerability ({severity} - {category}):** {comment_body}"
                    })
                    # Also add to the overall review body for visibility
                    overall_review_body.append(f"- 🚨 **{path}:{position} ({severity} - {category}):** {comment_body}")
                elif comment_body:
                     # If no specific line/path, add to overall comments
                    overall_review_body.append(f"- 🚨 **Security Vulnerability ({severity} - {category}):** {comment_body}")


        # --- Overall Review Comments ---
        if ai_review_json.get("overall_review_comments"):
            overall_review_body.append(f"\n## Overall Review Comments\n{ai_review_json['overall_review_comments']}")

        # --- Post the Review ---
        full_review_body = "\n".join(overall_review_body)
        if full_review_body.strip(): # Only post if there's content
            try:
                self.pr.create_review(
                    body=f"🤖 dhp-pr-review-bot reviewed this PR.\n\n{full_review_body}",
                    event="COMMENT", # Or "APPROVE" / "REQUEST_CHANGES" based on AI confidence/rules
                    comments=comments_for_github_review
                )
                print("Successfully posted PR review.")
            except Exception as e:
                print(f"Error posting PR review: {e}")
        else:
            print("No review content to post from AI. Skipping PR review creation.")

