name: PR Review Bot

on:
  pull_request:
    types: [review_requested]

jobs:
  review:
    if: |
      contains(github.event.requested_reviewer.login, 'dhp-pr-review-bot') ||
      contains(github.event.requested_team.name, 'dhp-pr-review-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: python pr_review.py
