name: PR Review Bot

on:
  pull_request:
    types: [review_requested]

jobs:
  review:
    # This job runs only if the 'dhp-pr-review-bot' user or team is requested as a reviewer.
    if: |
      contains(github.event.requested_reviewer.login, 'dhp-pr-review-bot') ||
      contains(github.event.requested_team.name, 'dhp-pr-review-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PR Review
        env:
          # GitHub Token for interacting with the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PR Number to identify the current Pull Request
          PR_NUMBER: ${{ github.event.pull_request.number }}
          # Repository name (e.g., 'owner/repo_name')
          REPO: ${{ github.repository }}
          # AWS Bedrock Knowledge Base ID (set this as a GitHub Secret)
          AWS_BEDROCK_KB_ID: ${{ secrets.AWS_BEDROCK_KB_ID }}
          # AWS Region where Bedrock is deployed (set this as a GitHub Secret, or hardcode if always same)
          AWS_REGION: ${{ secrets.AWS_REGION }}
        # Execute the new main bot file
        run: python pr_review_bot.py